<?php
/**
 * Protected storage for generated documents and cached remote assets.
 *
 * @package IDTA\PDF
 */

declare( strict_types=1 );

namespace IDTA\PDF;

defined( 'ABSPATH' ) || exit;

/**
 * Owns the plugin's directories under wp-content/uploads.
 *
 * No document is kept here. Documents are rendered when their URL is requested
 * and streamed straight out, so what remains under this directory is working
 * storage: the cache of customers' uploaded photos, which would otherwise be
 * fetched over the network on every render, and the engine's own scratch space.
 */
final class Filesystem {

	/**
	 * Directory name inside the uploads folder.
	 */
	private const DIR_NAME = 'idta-pdf';

	/**
	 * Absolute path to the plugin's upload directory.
	 *
	 * @return string
	 */
	public function base_dir(): string {
		$uploads = wp_get_upload_dir();

		return trailingslashit( $uploads['basedir'] ) . self::DIR_NAME;
	}

	/**
	 * Cache directory for localised remote assets.
	 *
	 * @return string
	 */
	public function cache_dir(): string {
		$dir = $this->base_dir() . '/cache';

		$this->ensure_dir( $dir );

		return $dir;
	}

	/**
	 * Temporary directory used by the PDF engine.
	 *
	 * @return string
	 */
	public function temp_dir(): string {
		$dir = $this->base_dir() . '/tmp';

		$this->ensure_dir( $dir );

		return $dir;
	}

	/**
	 * Create the base directory and its guards.
	 */
	public function ensure_base_dir(): void {
		$this->ensure_dir( $this->base_dir() );
	}

	/**
	 * Create a directory, with web access denied.
	 *
	 * @param string $dir Absolute path.
	 *
	 * @return bool Whether the directory exists and is writable.
	 */
	public function ensure_dir( string $dir ): bool {
		if ( ! wp_mkdir_p( $dir ) ) {
			return false;
		}

		$this->protect( $this->base_dir() );

		return wp_is_writable( $dir );
	}

	/**
	 * Write directory-listing and direct-access guards.
	 *
	 * Apache honours .htaccess; nginx and LiteSpeed do not, which is why
	 * downloads are always served through the download handler rather than by
	 * linking to these files.
	 *
	 * @param string $dir Absolute path.
	 */
	private function protect( string $dir ): void {
		$htaccess = $dir . '/.htaccess';

		if ( ! file_exists( $htaccess ) ) {
			$rules = "# Generated by IDTA PDF. Do not edit.\n"
				. "<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n"
				. "<IfModule !mod_authz_core.c>\n\tOrder allow,deny\n\tDeny from all\n</IfModule>\n";

			$this->put_contents( $htaccess, $rules );
		}

		$index = $dir . '/index.php';

		if ( ! file_exists( $index ) ) {
			$this->put_contents( $index, "<?php\n// Silence is golden.\n" );
		}
	}

	/**
	 * Write a file, preferring a direct write.
	 *
	 * The direct write comes first deliberately. Everything written here lives in
	 * the plugin's own directory under uploads, which it created and owns, so
	 * there is nothing for WP_Filesystem's credential handling to solve.
	 *
	 * The old order asked for WP_Filesystem first and, on the frontend, pulled in
	 * wp-admin/includes/file.php to get it. That had two costs: it dragged the
	 * admin file API into checkout requests, and — because that same file is what
	 * defines wp_tempnam() — it made an unrelated part of the image pipeline work
	 * or fatal depending on whether anything had written a file yet. That is why
	 * one document generated and the other did not, and why it looked arbitrary.
	 *
	 * @param string $file     Absolute path.
	 * @param string $contents File contents.
	 *
	 * @return bool
	 */
	public function put_contents( string $file, string $contents ): bool {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		if ( false !== file_put_contents( $file, $contents, LOCK_EX ) ) {
			return true;
		}

		// A host that blocks direct writes may still offer WP_Filesystem, but only
		// if the admin file API is already loaded. This will not load it.
		global $wp_filesystem;

		if ( ! $wp_filesystem instanceof \WP_Filesystem_Base && function_exists( 'WP_Filesystem' ) ) {
			WP_Filesystem();
		}

		if ( $wp_filesystem instanceof \WP_Filesystem_Base ) {
			return (bool) $wp_filesystem->put_contents(
				$file,
				$contents,
				defined( 'FS_CHMOD_FILE' ) ? FS_CHMOD_FILE : 0644
			);
		}

		return false;
	}

	/**
	 * Delete a file if it sits inside the plugin's storage.
	 *
	 * @param string $file Absolute path.
	 *
	 * @return bool
	 */
	public function delete( string $file ): bool {
		if ( '' === $file || ! $this->is_managed( $file ) || ! file_exists( $file ) ) {
			return false;
		}

		// wp_delete_file() returns void; report on the file's absence instead.
		wp_delete_file( $file );

		return ! file_exists( $file );
	}

	/**
	 * Whether a path lives inside the plugin's storage directory.
	 *
	 * Guards the download handler and delete routines against traversal.
	 *
	 * @param string $file Absolute path.
	 *
	 * @return bool
	 */
	public function is_managed( string $file ): bool {
		if ( '' === $file ) {
			return false;
		}

		$base = wp_normalize_path( $this->base_dir() );

		// Prefer realpath, which also resolves symlinks. It returns false for
		// paths that do not exist yet, so fall back to collapsing the path
		// lexically — otherwise unresolved ../ segments would pass the prefix
		// check below.
		$resolved = realpath( $file );

		$real = false !== $resolved
			? wp_normalize_path( $resolved )
			: $this->collapse_path( wp_normalize_path( $file ) );

		return str_starts_with( $real, trailingslashit( $base ) );
	}

	/**
	 * Collapse "." and ".." segments in a path without touching the filesystem.
	 *
	 * @param string $path Normalised path.
	 *
	 * @return string
	 */
	private function collapse_path( string $path ): string {
		$absolute = str_starts_with( $path, '/' );
		$out      = array();

		foreach ( explode( '/', $path ) as $segment ) {
			if ( '' === $segment || '.' === $segment ) {
				continue;
			}

			if ( '..' === $segment ) {
				array_pop( $out );

				continue;
			}

			$out[] = $segment;
		}

		return ( $absolute ? '/' : '' ) . implode( '/', $out );
	}
}
